import type { Metadata } from 'next'
import { siteConfig } from './site'

interface PageMetadataOptions {
  /** Page title without the site suffix. Omit for the home page. */
  title?: string
  description?: string
  /** Path of the page, e.g. `/about`. Used for the canonical URL and og:url. */
  path: string
}

// Generated by app/opengraph-image.tsx. Listed explicitly because a page-level `openGraph`
// object drops the image Next.js would otherwise inherit from the root segment.
const shareImage = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: `${siteConfig.name} — ${siteConfig.tagline}`,
}

/**
 * Builds per-page metadata. Next.js replaces (rather than merges) nested `openGraph` and
 * `twitter` objects, so every page gets the full set here instead of relying on the root layout.
 */
export function pageMetadata({ title, description = siteConfig.description, path }: PageMetadataOptions): Metadata {
  const fullTitle = title ? `${title} | ${siteConfig.name}` : `${siteConfig.name} | ${siteConfig.tagline}`

  return {
    title: { absolute: fullTitle },
    description,
    alternates: { canonical: path },
    openGraph: {
      title: fullTitle,
      description,
      url: path,
      siteName: siteConfig.name,
      type: 'website',
      locale: 'en_US',
      images: [shareImage],
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [shareImage],
    },
  }
}
